# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_call:
    

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      - name: ğŸ› ï¸ Restore tools
        run: dotnet tool restore
      - name: ğŸ–¨ï¸ Print current version info
        run: dotnet dotnet-gitversion
      - name: ğŸ“¦ Restore packages
        run: dotnet restore
      - name: ğŸ—ï¸ Build
        run: dotnet build
          -c Release
          --no-restore
          -p:IsCiBuild=true
      - name: ğŸ§ª Test
        run: dotnet test -c Release --no-build --no-restore
      - uses: actions/upload-artifact@v3
        with:
          name: nuget-packages
          retention-days: 1
          path: |
            **/*.nupkg
            **/*.snupkg